Lato: "'Lato', sans-serif"
Montserrat: "'Montserrat', sans-serif"
Montserrat+Alternates: "'Montserrat Alternates', sans-serif"
Montserrat+Subrayada: "'Montserrat Subrayada', sans-serif"
Bree Serif:  "'Bree Serif', serif"
Crimson+Text:  "'Crimson Text', serif"
EB+Garamond:  "'EB Garamond', serif"
Merriweather:  "'Merriweather', serif"
Merriweather+Sans:  "'Merriweather Sans', sans-serif"
Playfair+Display:  "'Playfair Display', serif"
Playfair+Display+SC:  "'Playfair Display SC', serif"
Oswald:  "'Oswald', sans-serif"
Roboto:  "'Roboto', sans-serif"
Roboto+Condensed:  "'Roboto Condensed', sans-serif"
