title: LEAF architecture
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
  - photon
metadata:
  description: Architectural Services
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
# logo: photon-logo.png
