color:
  key:
    hue: 110
  1:
    hueOffset: -120
  2:
    hueOffset: 180
  saturation: 22
  lightness:
    lighter: 75
    light: 66
    mid: 44
    dark: 33
    darker: 19
  foreground: '#333'
  background: 'hsla(255,100%,100%,.5)'
font: Fira+Sans+Condensed
font_display: Fira+Sans+Condensed
font_code: monospace
header_height: 10em
fitz: .5em
col: 18em
